Windows: Restore some old settings
grafana/grafana-build pull request #89
Opened 2023-06-29 14:16 UTC by zerok

During testing of the new nsis-based installer I discovered a couple of differences from the old version and tried to restore the old behaviour:

- Uninstalling should also remove the app from the "Add and remove..." listing again
- The service name was originally "Grafana" and has now been restored to it again
- Restored the old AppNames ("GrafanaOSS", "GrafanaEnterprise") to keep testing and docs consistent

2023-07-05 17:58 UTC, kminehart commented
god I hate the naming "GrafanaOSS". It's just Grafana.

i guess we have to leave it like this for now. It would make me so happy to get away from this naming though.

2023-07-05 18:00 UTC, kminehart requested changes

2023-07-06 13:50 UTC, kminehart commented on pipelines/package_names.go
> +	filename = filepath.Base(filename)
you may want to merge with main on this, this function had some improvements to handle non-tar.gz extensions and might affect your changes.

2023-07-06 13:51 UTC, kminehart commented on pipelines/package_names.go
> +	filename = filepath.Base(filename)
oh nvm I see you did already oops

2023-07-06 13:51 UTC, kminehart commented on scripts/packaging/windows/grafana.nsis
> +!endif
hahahaha you didn't have to do this but this does make me happy.

2023-07-06 13:52 UTC, kminehart approved these changes
Love it!

2023-07-06 18:52 UTC, kminehart commented
I'm going to merge this for you since @guicaulada opened a conflicting PR. I'd rather that he resolve those conflicts in his PR than make you wait even longer to get this merged.

2023-07-06 18:52 UTC, merged

2023-07-07 06:27 UTC, zerok commented
Thank you :) Forgot to set automerge -_-